files:
  included:
    - lib/**/*.rb
    - pakyow-core/lib/**/*.rb
    - pakyow-mailer/lib/**/*.rb
    - pakyow-presenter/lib/**/*.rb
    - pakyow-rake/lib/**/*.rb
    - pakyow-realtime/lib/**/*.rb
    - pakyow-support/lib/**/*.rb
    - pakyow-test/lib/**/*.rb
    - pakyow-ui/lib/**/*.rb
