sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  # - ruby-head
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d2966f0802fa60b226f
branches:
  only:
    - master
script: "bundle exec rake ci"
before_install: gem install bundler
addons:
    code_climate:
        repo_token: 5cbfd85e621316c736d7bb2ae9e1dc93689e0321095f21dfc2cf23a5335d71a1
