sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  # - ruby-head
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d2966f0802fa60b226f
branches:
  only:
    - master
script: "bundle exec rake ci"
before_install: gem install bundler
