language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
notifications:
  email: false
  hipchat: dc38d765431b4f0b3119274f433524@Conference Room
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d2966f0802fa60b226f
# whitelist
branches:
  only:
    - master
